Feature footer andry
Victor-Rochnyak/IceCream pull request #5
Opened 2022-06-23 22:13 UTC by shevalie30

[добавил свг спрайт соц иконок+html разметка+scss стили

2022-06-23 22:32 UTC, Victor-Rochnyak requested changes

2022-06-23 22:32 UTC, Victor-Rochnyak commented on src/partials/footer.html
> +
тебе надо обернуть весь код в теги <footer>

2022-06-23 22:32 UTC, Victor-Rochnyak commented on src/partials/footer.html
> +      <a class="footer__link" href="" aria-label="иконка giyhub">
aria-label="иконка giyhub <- опичатка в слове

2022-06-23 22:32 UTC, Victor-Rochnyak commented on src/partials/footer.html
> +          <use href="./img/sprite.svg#icon-giyhub"></use>
поменяй название svg с giygub на github )

2022-06-24 06:53 UTC, VitalinaKovbasiuk approved these changes

2022-06-24 12:16 UTC, shevalie30 commented on src/partials/footer.html
> +
оберну попозже мне главное увидеть что получилось

2022-06-24 12:16 UTC, shevalie30 commented on src/partials/footer.html
> +      <a class="footer__link" href="" aria-label="иконка giyhub">
исправил

2022-06-24 13:40 UTC, merged